name: Purge jsDelivr Cache

on:
  push:
    branches:
      - master

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge JSON and folders from jsDelivr
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/DevGeekPhoenix/zoobin-updates@latest/assetmap.json
            https://cdn.jsdelivr.net/gh/DevGeekPhoenix/zoobin-updates@latest/metadata.json
            https://cdn.jsdelivr.net/gh/DevGeekPhoenix/zoobin-updates@latest/assets/
            https://cdn.jsdelivr.net/gh/DevGeekPhoenix/zoobin-updates@latest/_expo/
            https://cdn.jsdelivr.net/gh/DevGeekPhoenix/zoobin-updates@latest/.expo/
